### PR TITLE
totally 5 file changes,  feel free to merge some and reject others.

### PR DESCRIPTION
**Pull request by Neutron3529**
"totally 5 file changes, `args.rs` for adding rounding mechanism, make blueprint file much smaller. `blueprint.rs` changes `if d.len() != 32` to `if d.len() < 32` in order to deal with manual pasted blueprint which may contains more line breaks. `data/building.rs` doing two things, firstly perform the real rounding, which may strip the size of blueprint, and another is adding names into the game, make output results more readable (which also adding a data file, `data/DYSON_DATA.rs`). Finally, lib.rs changes the flag to control whether rounding is desired, and using lazy_cell for initializing hashmaps contain the ids and corresponding names."

### CODE REVIEW

**Comment by Wesmania** [comment]
Hey, a contributor, awesome. I have some thoughts, I'll do one comment per feature so it's not a mess.

The rounding changes, I'm not 100% convinced. I avoided functionality that moves entities around, since I have no idea whether:

* it breaks blueprints,
* or worse, allows making blueprints not normally possible, which is kind of light cheating.

I did not use this myself of course. Does this rounding work in practice? If it does, then I guess it can be merged in, *if* we give a warning that it might break blueprints.

As for implementation, doing it with `binrw` attributes looks wrong and requires a very ugly mess of globals. We could implement it with `Visitor`, visiting all entities in blueprint and rounding the values after the blueprint is loaded, no globals needed.

**Comment by Wesmania** [comment]
With the hash part, I'm confused what the issue is. Do newer blueprints have line breaks between hash and data? If so, then IMO it would be better to `.trim()` the string first instead of accepting anything 32 bytes or longer.

**Comment by Wesmania** [comment]
Then the readable names feature. I'm 100% for it, with 2 caveats:
* Please describe where you scraped the names from so I can add English names too :D
* I'd like to make it optional somehow, or add language selection. Quick google suggests it's not easy with Serde without using globals, I'll think some more and maybe post another comment.

EDIT: Well, here's an okay-ish idea I came up with.
* Implement a `HumanReadableSerializer` that stores some info, but otherwise passes everything through serde_json's serializer.
* In `ser_item_id`, require `S` to derive `Any` and use runtime magic to try to downcast the serializer to `HumanReadableSerializer`. If we succeed, we can get info from it on how to print human readable info.
* Optionally, maybe store all these raw IDs in newtypes so we don't have to manually annotate every single one.

Sounds complicated to be honest, I'll try to implement it tomorrow maybe.

**Comment by Neutron3529** [comment]
...

I've wrote a lot of replies and happened to lose all of them

the rounding is fine, since it modify the 0.00000xxxx to 0 directly
it might be better to further rounding `-0.0` to `0.0` (.round() will keep the sign, which is not what we desired)

As for i18n, type -itemIds after using `78963214o` open the game console is enough.
Btw, I wrote 2 features, one for Chinese and one for English. (#7 )

**Comment by Neutron3529** [comment]
> With the hash part, I'm confused what the issue is. Do newer blueprints have line breaks between hash and data? If so, then IMO it would be better to `.trim()` the string first instead of accepting anything 32 bytes or longer.

This is my usecase. I download blueprint from bbs, paste it directly in my IDE, since my ide always adding `\n` at the end of the file, and thus the program cannot recognize such blueprint.

**Comment by Wesmania** [comment]
> This is my usecase. I download blueprint from bbs, paste it directly in my IDE, since my ide always adding `\n` at the end of the file, and thus the program cannot recognize such blueprint.

Okay, sounds reasonable. A call to `.trim()` won't break regular files anyway.

**Pull request closed without merging**
